### PR TITLE
added MoCo loss and time series augmentations

### PR DESCRIPTION
**Pull request by kashif**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kashif** [comment]
I guess you can cherry pick this commit: https://github.com/kashif/gluon-ts/commit/6b0c1476f592c73d7c15dbaf54054f3236f319ba

**Comment by kashif** [comment]
@vafl dont merge just yet ... for some reason SimCLR is giving me nans here whereas my independent version works so let me debug it...

**Comment by vafl** [comment]
Thanks @kashif

**Comment by kashif** [comment]
@vafl ok fixed the issue was my fault

**Comment by kashif** [comment]
@vafl I've added a number of time series augmentation methods that work on `[B,T,F]` tensors, all of which can be composed via the `RandomApply` class.

**Comment by vafl** [comment]
Nice, thanks @kashif

Can we maybe get rid of the duplication between pytorch and numpy augmentations?
We could maybe remove the numpy version (its not used right now, is it?) or have an interface where torch uses the numpy variant or vice versa.

**Comment by kashif** [comment]
yes @vafl I'll remove the numpy version...

**Pull request merged**
